name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build APK
        run: |
          pip install "flet[all]" pdfplumber
          
          # 1. Quitamos TU main.py de en medio (lo renombramos)
          # Así 'flet create' no verá que ya existe un main.py y no dará error
          mv main.py mi_codigo.py
          
          # 2. Creamos la estructura (ahora NO dará error porque no hay conflicto)
          flet create .
          
          # 3. Borramos el main.py de ejemplo que acaba de crear Flet
          rm main.py
          
          # 4. Devolvemos TU código a su sitio original
          mv mi_codigo.py main.py
          
          # 5. Fabricamos el APK con el icono y el nombre
          flet build apk --icon torre-de-control.png --name "SDP-COM"

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SDP-COM-App
          path: build/apk/*.apk
