name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build APK
        run: |
          # 1. Instalar herramientas
          pip install flet pdfplumber
          
          # 2. Aceptar licencias usando la ruta de sistema fija de GitHub
          yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true
          
          # 3. Construir (Flet usará el flet.toml que creaste a mano)
          flet build apk

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SDP-COM-App
          path: build/apk/*.apk
